"""Audience application 所需的最小仓储协议。"""

from typing import Protocol


class AudienceRepository(Protocol):
    def get_account_audience_relationship(self, account_id: str): ...
    def get_account_memory_preference(self, account_id: str): ...
    def delete_account_persona_memory(self, account_id: str): ...
    def get_audience_relationship(self, viewer_key: str): ...
    def upsert_audience_relationship(self, relationship: dict): ...
    def upsert_account_audience_relationship(self, relationship: dict): ...
    def claim_recent_nickname_change(self, account_id: str, cutoff: str, now: str): ...
